name: AWS Marketplace Updates Monitor

on:
  schedule:
    - cron: "0 12 * * *"  # Runs daily at 12:00 UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  monitor:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"  # Install Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install necessary libraries

    - name: Run documentation check
      run: python monitor.py  # Execute the monitoring script

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}  # Use GitHub Personal Access Token
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add snapshots/ || true
        git commit -m "Updated AWS Marketplace documentation snapshots" || true
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git main || true
